### ISSUE TITLE
Add new maintainers

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt-fmpp#8]
volunteers?

**Comment by MasseGuillaume** [comment]
Yes!

**Comment by eed3si9n** [comment]
Welcome to the team

**Comment by SethTisue** [comment]
Closing, but if anyone else is interested in helping, feel free to step forward.

**Comment by MasseGuillaume** [comment]
In terms of publishing to Sonatype, how do we proceed?

**Comment by eed3si9n** [comment]
I'd be happy to automate that using tag push.

**Comment by MasseGuillaume** [comment]
Ok, I can do the CI setup with something like: https://github.com/sbt/sbt-unidoc/blob/develop/.github/workflows/release.yml

If you can fill the secret env variables, I'm happy to do the rest.
